[package]
name = "steiner_tree"
version = "0.1.0"
authors = ["5hir0kur0 <12101162+5hir0kur0@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
